done
Kira-ka/Dagger2Homework pull request #1
Opened 2024-05-14 09:38 UTC by Kira-ka

2024-05-18 09:20 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-05-18 09:20 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Здесь теперь возможно утечка памяти. Так как ViewModel живет дольше чем активити, она будет держать ссылку на старую активити в случае пересоздания

2024-05-18 09:20 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelKey.kt
> +@Retention(AnnotationRetention.RUNTIME)
Эти аннотации можно убрать. Даггер ничего в рантайме не процессит

2024-05-18 09:20 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
Можно убрать

2024-05-18 09:20 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun provideApp(): App
А зачем тебе именно App? тебе же по идее контекст просто нужен

2024-05-18 09:20 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ActivityComponent.kt
> +    @Singleton
Мне кажется тебе нужен отдельный скоуп. Который ниже чем синглтон в аппкомпонент
Также лучше разбить флоу на два: мутабельный и имуттабельный, чтобы у тебя в ресивере не было возможности эмитить события

2024-05-20 04:51 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ViewModelKey.kt
> +@Retention(AnnotationRetention.RUNTIME)
Убрал

2024-05-20 04:57 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun provideApp(): App
чтобы квалифаеры не использовать

2024-05-20 05:19 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ActivityComponent.kt
> +    @Singleton
Флот разбил на 2. Первый коммент не понял: второй скоуп ниже чем синглтон в аппкомпоненте? Я же пометил аннотацией синглтон Активити компонент и флоу будет синглтоном в рамках Активити компонента? Или получается, что сам Активити компонент будет синглтоном в рамках аппкомпонента из за этой аннотации?

2024-05-20 05:20 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Это получается из за того что я модуль ViewModelFactoryModule добавил в аппкомпонент?

2024-05-25 12:35 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Нет, это потому что нельзя держать в ViewModel которая живет дольше чем activity ссылку на эту самую актвити

2024-05-25 12:36 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun provideApp(): App
А чем плохи квалифаеры?

2024-05-25 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ActivityComponent.kt
> +    @Singleton
Ну у тебя по идее должно быть соотношение скоуп к слою компонентов 1 - 1. Тоесть на все компоненты что создаются в активити, например, АктивитиСкоуп, для фрагментов ФрагментСкоуп. А для аппликейшена Singleton

2024-05-30 06:30 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
торможу, исправил

2024-05-30 06:33 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ProducerScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
убрал

2024-05-30 06:33 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun provideApp(): App
лень было писать) исправил

2024-05-30 07:39 UTC, Kira-ka commented on app/src/main/java/ru/otus/daggerhomework/ActivityComponent.kt
> +    @Singleton
исправил

2024-06-03 06:00 UTC, merged